



name: "RNN"
task: "BuyChargeTask" # HotelReservationTask or BuyChargeTask
seed: 11111

model:
  layer1:
    layer: "input"
    shape: ${model_params.max_seq_len}
  layer2:
    layer: "TokenAndPositionEmbedding"
    vocabulary_size: ${model_params.vocab_size}
    sequence_length: ${model_params.max_seq_len}
    embedding_dim: ${model_params.embedding_dim}
  layer3:
    layer: "dropout"
    rate: 0.2
  layer4:
    layer: "rnn"
    type: "GRU" # GRU or LSTM
    bidirectional: true
    num_units: 150
    activation: "elu"
    return_sequences: true
    use_bias: true
    kernel_regularizer:
      type: "L2"
      value: 1e-4
    recurrent_regularizer:
      type: "L2"
      value: 1e-4
    bias_regularizer:
      type: "L2"
      value: 1e-4
    activity_regularizer:
      type: "L2"
      value: 1e-5
    dropout: 0.1
    recurrent_dropout: 0.1
  layer5:
    layer: "dense"
    activation: "softmax"
    dim: 12
    time_distributed: true

model_params:
  max_seq_len: 45
  num_words: 250
  vocab_size: 300 # "num_words" + 50
  batch_size: 32
  epochs: 3
  steps_per_epoch: 5000
  validation_steps: 3000
  embedding_dim: 300
  # for now only Adam optimizer is supported. More optimizers will be added if needed...
  optimizer:
    type: "adam"
    learning_rate: 0.001
  # for now only categorical_crossentropy loss is supported. More optimizers will be added if needed...
  loss: "categorical_crossentropy"
  metrics: ["precision", "recall", "accuracy"]

data:
  # if you are loading data from pickle files, their name must be
  # train_data.pickle, validation_data.pickle and test_data.pickle if use_test_set is True
  from: "pickle" # text or pickle
  data_dir: "../data"
  # data split ratio
  split: 0.2
  # if true, "2*split" percent of data is taken away for validation and test set and the rest is for train.
  # else, "split" percent of data is taken away for validation and the rest is for train.
  use_test_set: false
  add_sos_eos: false # Add <sos> and <eos> at the beginning and end of sentence
  labels: {
    "PAD": 0,
    "O": 1,
    "charge_type": 2,
    "bnumber": 3,
    "pnumber": 4,
    "amount": 5,
    "operator": 6,
    "unit": 7,
    "charge_type_post": 8,
    "bnumber_post": 9,
    "pnumber_post": 10,
    "operator_post": 11,
    "<sos>": 12,
    "<eos>": 13}






