
name: "ConvSeq2Seq" # Model name
task: "BuyChargeTask" # HotelReservationTask or BuyChargeTask
seed: 11111

# model configs
model_params:
  max_seq_len: 45
  num_words: 250
  vocab_size: 300 # "num_words" + 50
  batch_size: 32
  epochs: 30
  steps_per_epoch: 5000
  validation_steps: 3000
  embedding_dim: 300
  hidden_dim: 300 #hidden size
  clip: 0.1 #gradient clipping
  dropout: 0.25
  kernel_size: 3 #encoder/decoder CNN kernel size
  encoder_layers: 2 #number of layers of the encoder
  decoder_layers: 2 #number of layers of the decoder
  # for now only Adam optimizer is supported. More optimizers will be added if needed...
  optimizer:
    type: "adam"
    learning_rate: 0.001
  # for now only categorical_crossentropy loss is supported. More optimizers will be added if needed...
  loss: "CrossEntropyLoss"


callbacks:
  TensorBoard:
    log_dir: /media/SSD1TB/khayati/projects/nlu/intent_slot_filling/output/logs/${name}

save_model_dir: /media/SSD1TB/khayati/projects/nlu/intent_slot_filling/output/model/${name}

data:
  # if you are loading data from pickle files, their name must be
  # train_data.pickle, validation_data.pickle and test_data.pickle if use_test_set is True
  from: "pickle" # text or pickle
    # Path of directory where templates.txt or train_task.pickle, validation_task.pickle, and test_task.pickle files are there.
  data_dir: "/media/SSD1TB/khayati/projects/nlu/intent_slot_filling/data"
  save_data_dir: /media/SSD1TB/khayati/projects/nlu/intent_slot_filling/output/data_dump/${name}
  # data split ratio
  split: 0.2
  # if true, "2*split" percent of data is taken away for validation and test set and the rest is for train.
  # else, "split" percent of data is taken away for validation and the rest is for train.
  use_test_set: false
  add_sos_eos: true # Add <sos> and <eos> at the beginning and end of sentence
  augmentation: 0.5 # Augemntation Percent,  set 0 for no augmentation
  labels: {
    "PAD": 0,
    "O": 1,
    "charge_type": 2,
    "bnumber": 3,
    "pnumber": 4,
    "amount": 5,
    "operator": 6,
    "unit": 7,
    "charge_type_post": 8,
    "bnumber_post": 9,
    "pnumber_post": 10,
    "operator_post": 11,
    "<sos>": 12,
    "<eos>": 13}